version: '3.7'
services:
  REPONAME_DOCKER:
    build: .
    image: qmcgaw/REPONAME_DOCKER
    container_name: REPONAME_DOCKER
    ports:
      - 8000:8000/tcp
    environment:
      - ROOTURL=
      - GOTIFYURL=
      - GOTIFYTOKEN=
      - TZ=America/Montreal
    depends_on:
      - postgres
    restart: always
  postgres:
    build: postgres
    image: postgres
    container_name: postgres
    expose:
      - 5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # For Windows only
      # - postgres:/var/lib/postgresql/data
    restart: always
  # TODO redis:
